import { items as spanishItems, monsters as spanishMonsters, rooms as spanishRooms } from "./originalWorld";
import type { Item, Monster, Room } from "./World";

/**
 * The same world in English: every name and every description translated,
 * the numbers and the map untouched. The Spanish original stays beside it as
 * the source, so the two cannot drift apart in anything but words.
 */
const ITEM_NAMES: Readonly<Record<string, string>> = {
  "llave de laton": "brass key",
  "cristal magico": "magic crystal",
  "llave de casa": "house key",
  "llave de la verja": "gate key",
  "llave del puente": "bridge key",
  "llave del gnomo": "gnome's key",
  barca: "boat",
  "llave de la despensa": "pantry key",
  diario: "newspaper",
  matamoscas: "fly swatter",
  "espada de madera": "wooden sword",
  espada: "sword",
  "espada venenosa": "poisoned sword",
  Thurmei: "Thurmei",
  camisa: "shirt",
  "escudo de madera": "wooden shield",
  "escudo de escamas": "scale shield",
  escudo: "shield",
  Rharmei: "Rharmei",
  caramelo: "sweet",
  judia: "bean",
  manzana: "apple",
  naranja: "orange",
  pocima: "potion",
};

const MONSTER_NAMES: Readonly<Record<string, string>> = {
  "mosca acida": "acid fly",
  mosca: "fly",
  mosquito: "mosquito",
  polilla: "moth",
  cucaracha: "cockroach",
  raton: "mouse",
  "rana venenosa": "poison frog",
  "planta carnivora": "carnivorous plant",
  "raton salvaje": "wild mouse",
  "escorpion dorado": "golden scorpion",
  trucha: "trout",
  "trucha asesina": "killer trout",
  "minimonstruo aquatico": "small water monster",
  lobo: "wolf",
  "lobo asesino": "killer wolf",
  ogro: "ogre",
  "gnomo de puente": "bridge gnome",
  murcielago: "bat",
  aranya: "spider",
  vampiro: "vampire",
  "aranya gigante": "giant spider",
  "monstruo aquatico enorme": "enormous water monster",
};

const ROOM_NAMES: Readonly<Record<string, string>> = {
  Bienvenida: "Welcome",
  "Usa las llaves": "Use the keys",
  "Comedor sur": "Dining room, south",
  Salita: "Sitting room",
  "Huerto de pepinos": "Cucumber patch",
  "Huerto de tomates": "Tomato patch",
  Caminito: "Little path",
  Despensa: "Pantry",
  "Aprende a atacar": "Learn to attack",
  Comedor: "Dining room",
  Recibidor: "Hall",
  Patio: "Yard",
  "Huerto de Judias": "Bean patch",
  Manzanos: "Apple trees",
  Ciruelos: "Plum trees",
  Banyo: "Bathroom",
  Habitacion: "Bedroom",
  "Comedor norte": "Dining room, north",
  Cocina: "Kitchen",
  "Huerto de calabazas": "Pumpkin patch",
  Naranjos: "Orange trees",
  Entrada: "Gate",
  Nogal: "Walnut trees",
  Cueva: "Cave",
  "Lago interno": "Underground lake",
  "Centro del lago": "Middle of the lake",
  "Rio salvaje": "Wild river",
  Rio: "River",
  "Bosque oscuro": "Dark forest",
  "Rio oscuro": "Dark river",
  "Bosque tenebroso": "Gloomy forest",
  "Bosque sombrio": "Shadowy forest",
  "Bosque humedo": "Damp forest",
  Bosque: "Forest",
  "Claro del Bosque": "Forest clearing",
  "Puente del bosque": "Forest bridge",
};

const CAVE = "The tunnel of the dark, gloomy cave goes on. The walls are damp and\nwater can be heard running somewhere far off. Walk carefully, or you\nwill slip or trip.";
const FOREST = "The forest stretches out, dark and mysterious. The light blurs\nthrough the leaves. You can hear the animals and the forest's other\ninhabitants.";
const DARK_FOREST = "Though it is day, barely a glimmer of light gets in. Bushes, trees\nand brambles make the going hard. Something moves in the dark.";
const DAMP_FOREST = "Little light comes through the leaves of the trees. Brambles and\nbushes give way to a small stream. Something moves in the dark.";

const TEXTS: Readonly<Record<string, string>> = {
  "0,0": "Welcome to this adventure game.\nThis is the welcome room, where you will learn to move.\nThe commands are:\n 'north',\n 'south',\n 'east',\n 'west'.\nTry going to the next room to the 'east', and coming back 'west'.",
  "0,1": "In this room you will learn to take things and open locked doors.\nThe commands are:\n 'take',\n and the ones for moving.\nIf you go north straight away you will not be able to; try it.\nThen take the key ('take') and go north.",
  "0,2": "It is the south end of your dining room. Soft light comes in from the\nsitting room, and the chairs are waiting for your guests.",
  "0,3": "It is the sitting room of your house; the light comes in through the\nwindow and the curtains blur the outside. You can see your armchair,\na small table with a candlestick, and shelves with several books.",
  "0,4": "By the south fence of your farm you have the cucumber patch. They\nbarely lift a finger off the ground, but you are already licking your\nlips at the thought of them.",
  "0,5": "By the south fence of your farm you have the tomato patch. They are\nstill green, but it looks like a very good harvest this year.",
  "0,6": "A pretty little path runs off to the east, the farthest part of your\nfarm.",
  "0,7": "This is the end of your little path; to the north are the fruit trees.\nYou have always liked walking here in spring to see the blossom.",
  "1,0": "At last you have got into the pantry!\nNow you can start cooking for your guests.\nCONGRATULATIONS!",
  "1,1": "It is time you learnt to attack your enemies. Go carefully, because\nthey will defend themselves.\nThere is only one command:\n 'attack'.\nFor that you first need a weapon. Find one, take it, and attack.\nWhen you win you can go on.",
  "1,2": "You are in the dining room of your house; outside it is a glorious day\nand you are expecting company. Today you have decided to lay on a\nfeast! The hall is to the west, the sitting room to the south, and the\nkitchen to the west.",
  "1,3": "It is a small hall, but a welcoming one. It is plainly decorated but\nhas a coat rack to leave a jacket on.\nFrom here you can go straight to the sitting room, the dining room and\nthe kitchen.",
  "1,4": "It is a splendid day and you are in the garden of your farm. Here you\ncan see several flowers you planted, and a fountain. Vegetable patches\nsurround you, and farther east are the fruit trees.",
  "1,5": "A pretty bean patch opens up in front of you. You planted them only a\nfew weeks ago, but they are already in flower. The strong yellow of\nthe flowers stands out against the green of the plants.",
  "1,6": "These are your apple trees. The rains have been generous this year and\nyou will have a good harvest. There are already a few apples, but most\nare too green.",
  "1,7": "You have always liked this part of the farm. The plum trees have red\nleaves and give it a very fresh look. The river is to the north, and\nyour house to the south-west.",
  "2,0": "This is the bathroom of your house. It is rustic, but it works. You\nbought the bath recently, and beside it the towels are neatly folded.\nTo the south is the pantry.",
  "2,1": "It is the room where you sleep. You have a bed of worked wood, with\nplenty of blankets against the cold, and a dresser where you keep your\nclothes. From the bedroom you can reach the dining room and the\nbathroom.",
  "2,2": "It is the north end of your big dining room. The table is extended for\nthe occasion and every place is laid. From here you can reach the\nkitchen and your bedroom.",
  "2,3": "This is your kitchen. You are pleased with your new wood-fired oven;\nit cooks wonderfully. You have everything ready to make the meal, but\nthe ingredients are missing. You would have to fetch them from the\npantry.",
  "2,4": "This is your pumpkin patch. They have barely begun to grow, but you\ndepend on them to eat this autumn. You cannot help wondering whether\nto take one to your parents.",
  "2,5": "Here you have one of your hardest-suffering crops. You do not usually\nget many oranges, but you like them far too much. Their colour and\nscent are wonderful to you.",
  "2,6": "Here is the north gate of your farm. Two magnificent cypresses and\nplenty of bushes crown it. You usually keep the gate shut; you have\nnever liked going into the forest. To the north is the river.",
  "2,7": "Big walnut trees spread over this part of your farm. They are\nespecially interesting because, though their fruit is not as good as\nthe apples, they are hardy and get you through the winters.",
  "3,0": CAVE,
  "3,1": CAVE,
  "3,2": "An immense underground lake opens up before you. It is dark and you\ncan barely see, but you sense something moving to the east.\nYou need a boat to get to the middle of the lake.",
  "3,3": "You are in the middle of the lake in a small, fragile boat.\nIt is the home of Troildhem, an incredible, mysterious monster.\nYou had seen one like it before, but smaller.\nTroildhem is several metres tall, with a dozen tentacles with eyes\non them.",
  "3,4": "Here the river turns wild, but there is a bridge that lets you cross\nsafely to the other bank. The bridge has to be unlocked with a key\nbefore you can cross.",
  "3,5": "The river runs through here. You cannot cross, but farther west there\nis a bridge.",
  "3,6": "Your farm runs down to this river. To the north is the mysterious\nforest, but you cannot cross here.",
  "3,7": "The river widens and its waters grow calm; there are plenty of fish,\nbut something stirs beneath the surface.",
  "4,0": CAVE,
  "4,1": CAVE,
  "4,2": CAVE,
  "4,3": DARK_FOREST,
  "4,4": "The north bank of the river is dismal. Strange noises can be heard,\nand you sense a curse. Here is the bridge that crosses to the south\nbank; the air feels hostile and urges you across.",
  "4,5": "The river flows under the rocks and the roots of the forest's trees.\nThe sounds of the forest grow louder and you feel watched.",
  "4,6": "A gap between brambles and bushes lets you into the gloomy forest.\nLight is scarce and the shadows are threatening.",
  "4,7": DARK_FOREST,
  "5,0": "The tunnel of the dark, gloomy cave goes on. A great cobweb blocks\nthe way south. One careless move could make you its prey.",
  "5,1": CAVE,
  "5,2": "The tunnel of the dark, gloomy cave goes on. The walls are damp, and\nthe sound of water grows louder. Walk carefully, or you will slip or\ntrip.",
  "5,3": "The forest is dark, and beside you you have found a great wall of\nsolid rock to the west: the mountain, probably.",
  "5,4": DAMP_FOREST,
  "5,5": FOREST,
  "5,6": "The forest stretches out, dark and mysterious. You are in a small\nclearing where the sky can be seen. You notice the forest is\nrestless.",
  "5,7": FOREST,
  "6,0": CAVE,
  "6,1": CAVE,
  "6,2": "You are inside the cave; it is dark and gloomy. The walls are damp and\nwater can be heard running somewhere far off. You try to look ahead,\nbut it seems to have no end.",
  "6,3": "The forest is dark, and beside you you have found a great wall of\nsolid rock to the west: the mountain, probably. You notice the rock\nis damp; there is very likely a cave.",
  "6,4": "Little light comes through the leaves of the trees. Brambles and\nbushes give way to a small stream. A bridge crosses the stream to the\neastern part of the forest; there, under a tree, is the house of a\ntroll you will have to get past if you want to go east.",
  "6,5": DARK_FOREST,
  "6,6": "The forest stretches out, dark, mysterious and restless. You are in a\nsmall clearing where the sky can be seen.",
  "6,7": "In this part of the forest the light begins to fail. Tangles of\nbushes and brambles slow your steps. You notice something moving\namong the shadows.",
  "7,0": CAVE,
  "7,1": CAVE,
  "7,2": "You are a few steps inside the cave. Cold, damp air reaches you from\nwithin. You try to see where it ends, but you cannot. You hear\nmurmurs from deep inside.",
  "7,3": "Little light comes through the leaves of the trees. A tangle of\nclimbing plants stirs to the west: it is the mouth of a cave. You\nfeel a presence watching you.",
  "7,4": DAMP_FOREST,
  "7,5": FOREST,
  "7,6": FOREST,
  "7,7": FOREST,
};

const translate = (table: Readonly<Record<string, string>>, name: string) => table[name] ?? name;

export const items: readonly Item[] = spanishItems.map((item) => ({ ...item, name: translate(ITEM_NAMES, item.name) }));
export const monsters: readonly Monster[] = spanishMonsters.map((monster) => ({ ...monster, name: translate(MONSTER_NAMES, monster.name), drops: translate(ITEM_NAMES, monster.drops) }));
export const rooms: Readonly<Record<string, Room>> = Object.fromEntries(
  Object.entries(spanishRooms).map(([where, room]) => [
    where,
    { ...room, name: translate(ROOM_NAMES, room.name), holds: translate(ITEM_NAMES, translate(MONSTER_NAMES, room.holds)), text: TEXTS[where] ?? room.text },
  ]),
);
