name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run deploy

      - name: Checkout destination repository
        uses: actions/checkout@v4
        with:
          repository: drpicox/drpicox.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: gh-pages

      - name: Copy built files
        run: |
          rm -rf gh-pages/*
          cp -r out/* gh-pages/
          touch gh-pages/.nojekyll
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy Next.js build"
          git push
